### ISSUE TITLE
Update engine

### ISSUE THREAD

**Issue by jaydson** [gserrano/smeagol#3]
As smeagol is now using some of the new ES2015 features (which was introduced in Node.js v.6), the `engines` property should be changed to something like:  

```
{ "engines" : { "node" : ">=6.0.0" } }
```

See more: https://docs.npmjs.com/files/package.json#engines

With the current `package.json` anyone using smeagol running on a Node.js version lower than 6 will fail.

**Comment by gserrano** [comment]
Thanks @jaydson !
